version: '3.7'
services:
  postgres:
    image: postgres:11.5
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin@123
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - 15432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data: