spring:
  main:
    allow-bean-definition-overriding: true
  liquibase:
    change-log: classpath:liquibase/changelog-master.yml
    enabled: false
  profiles:
    active: local


cbar:
  url: https://www.cbar.az/currencies



