server:
  port: 8082
  servlet:
    application-display-name: currency-report

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:15432/currency?stringtype=unspecified
    username: admin
    password: admin@123
  jpa:
    show-sql: false
    properties:
      hibernate:
        hbm2ddl:
          auto: none


#    url: jdbc:postgresql://localhost:15432/currency?stringtype=unspecified
#    username: admin
#    password: admin@123